### PR TITLE
Changing labels on exchange search to include on and uuid

### PR DESCRIPTION
**Pull request by hfpmartins**

### CODE REVIEW

**Review by gregoryrinaldi — DISMISSED** [review]

**Comment by hfpmartins** [comment]
testme

**Comment by hfpmartins** [comment]
test me

**Comment by hfpmartins** [comment]
test me

**Review by gregoryrinaldi — DISMISSED** [review]

**Comment by hfpmartins** [comment]
test me

**Review by gregoryrinaldi — APPROVED** [review]

**Pull request merged**
