### PR TITLE
Unionvms 2275 organizations endpoints contacts

### PR DESCRIPTION
**Pull request by ansgarkroger**
This fixes the missing endpoints tab.

### CODE REVIEW

**Review by hfpmartins — DISMISSED** [review]

**Review by hfpmartins — DISMISSED** [review]
I was too quick to the review... please don't merge it!

**Comment by ansgarkroger** [comment]
I have updated the base of the pull request to be the dev branch

**Comment by ansgarkroger** [comment]
test me

**Review by sandrasvensson — APPROVED** [review]
Ok 👍

**Pull request merged**
