### PR TITLE
Add sales frontend to dev

### PR DESCRIPTION
**Pull request by MathiasBulte**

### CODE REVIEW

**Comment by sandrasvensson** [comment]
Hi @MathiasBulte Can I add a comment to this as well? :-)

**Comment by hfpmartins** [comment]
Hi @MathiasBulte ... Are you guys using jasmine for unit testing? Is it something that you plan to add later? Also it would be very cool if you could use JSDOC within your code. Is it something that you can also do?

**Comment by sandrasvensson** [comment]
Hi again @MathiasBulte , 

I've not been able to go through each file in detail but it would be helpful if you can come back to me on below three notes. 

**1.** Are you using the Gulp.js file? We've in a previous sprint removed this file since it was outdated and not in used. Please remove this one if you're not using it.

**2.** If possible - please specify what added shared files simpleExport.js, groupLineInput.js, stResetSearch.js is in use for and how to use them.

**3.** I'm not sure why proxiesDotNetSales.yaml and proxiesJava.yaml is added and who is using it? If these files are needed in the root, please update readme file on how to use them for developing.

In a future sprint it would be great if you can plan to add jsDoc and unit testing for all SalesFiles.

**Comment by stainii** [comment]
Hi guys,

Mathias has removed the Gulpfile, the .NET-proxies and has added JSdoc. Also, he has moved the "shared" files, which were actually sales-specific, to a sales folder.

I have checked in a little bug fix.

As for Javascript unit testing: this is not planned at the moment. It does not fit the tight planning either, unfortunately. After the big production release, I hope we can re-evaluate what's needed extra.

**Review by sandrasvensson — APPROVED** [review]
Ok!

**Review by hfpmartins — APPROVED** [review]
Ok

**Pull request merged**
