### PR TITLE
Usm fixes

### PR DESCRIPTION
**Pull request by ansgarkroger**
This pull request contains the fronted fixes performed by the Athens team and committed to SVN.

### CODE REVIEW

**Comment by ansgarkroger** [comment]
I have updated the base of the pull request to be the dev branch

**Comment by ansgarkroger** [comment]
test me

**Review by sandrasvensson — COMMENTED** [review]
**Some comments and questions to `updateMyContactDetails.html`:** 

- Would it be possible to add all copy for translation purpose to a separate file within the i18n folder?


- For language consistency in the application maybe we can write just “invalid” and “required”? Rather than “E-Mail is required / invalid”

- Can we create a regex. For e-mail address instead of using type=email since a valid e-mail address then can be for example: email@1.2. 
**Suggestion:** `ng-pattern="/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/"`


- Can we allow dash in the regex for phone number? (alternative write a placeholder so the user understands the format)
**Suggestion:** `ng-pattern="/^\+{0,1}[0-9- ]+$/"`

**Review by sandrasvensson — APPROVED** [review]
Looks ok I think :-)

**Pull request merged**
